import { Badge, Button } from "@astryxdesign/core";
import { useMutation, useQuery } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { RequestError } from "../components/InlineAlert";
import { api } from "../lib/api/client";
import type { ListResponse, ToolDefinition } from "../lib/api/types";

export function ToolsPage() {
  const [selected, setSelected] = useState<string>();
  const [argumentsText, setArgumentsText] = useState("{}");
  const [parseError, setParseError] = useState<string>();
  const [result, setResult] = useState<unknown>();
  const tools = useQuery({ queryKey: ["tools"], queryFn: () => api.request<ListResponse<ToolDefinition>>("/api/v2/tools") });
  const active = useMemo(() => tools.data?.data.find((tool) => tool.name === selected), [tools.data, selected]);
  const run = useMutation({ mutationFn: ({ name, args }: { name: string; args: Record<string, unknown> }) => api.request<unknown>(`/api/v2/tools/${encodeURIComponent(name)}/run`, { method: "POST", body: { arguments: args } }), onSuccess: setResult });
  function execute() { if (!active) return; try { const parsed: unknown = JSON.parse(argumentsText); if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) throw new Error("Arguments must be a JSON object."); setParseError(undefined); setResult(undefined); run.mutate({ name: active.name, args: parsed as Record<string, unknown> }); } catch (error) { setParseError(error instanceof Error ? error.message : "Invalid JSON"); } }
  return <div className="page"><section className="page-intro"><div><p className="eyebrow">Action registry</p><h2>Tools are explicit capabilities, not ambient powers.</h2><p>Inspect every authorized schema, risk class, timeout, and raw execution result before allowing agents to call it.</p></div></section><div className="master-detail"><section className="panel master-list">{tools.error ? <RequestError error={tools.error} /> : tools.isPending ? <p className="muted-copy">Loading tools…</p> : tools.data?.data.length ? <div className="record-list">{tools.data.data.map((tool) => <button key={tool.name} className={tool.name === selected ? "record-row record-row--active" : "record-row"} onClick={() => { setSelected(tool.name); setArgumentsText("{}"); setResult(undefined); }}><span className="record-row__mark">⚙</span><span><strong>{tool.name}</strong><small>{tool.description ?? "Hub tool"}</small></span><Badge variant={tool.risk === "high" ? "warning" : "neutral"} label={tool.risk} /></button>)}</div> : <p className="muted-copy">No tools registered.</p>}</section><section className="panel detail-panel">{!active ? <div className="detail-empty"><span>⚙</span><h3>Select a tool</h3><p>Its schema and isolated execution console will appear here.</p></div> : <><header className="detail-panel__header"><div><p className="eyebrow">Tool definition</p><h3>{active.name}</h3><p>{active.timeoutMs.toLocaleString()} ms timeout</p></div><Badge variant={active.risk === "high" ? "warning" : "teal"} label={`${active.risk} risk`} /></header><p className="tool-description">{active.description ?? "No description provided."}</p><section><p className="eyebrow">Input schema</p><pre className="json-preview">{JSON.stringify(active.inputSchema ?? active.input_schema ?? {}, null, 2)}</pre></section><label className="native-field"><span>Arguments JSON</span><textarea rows={7} value={argumentsText} onChange={(event) => { setArgumentsText(event.target.value); }} spellCheck={false} /></label>{parseError ? <p className="field-error">{parseError}</p> : null}{run.error ? <RequestError error={run.error} /> : null}<Button label="Run tool" variant="primary" isLoading={run.isPending} onClick={execute} />{result !== undefined ? <section><p className="eyebrow">Execution result</p><pre className="json-preview">{JSON.stringify(result, null, 2)}</pre></section> : null}</>}</section></div></div>;
}
